name       : vimix-gtk-theme
version    : '20230909'
release    : 10
source     :
    - https://github.com/vinceliuice/vimix-gtk-themes/archive/refs/tags/2023-09-09.tar.gz : 4f865b79d35abd459c9b9f0022ca0330539442761c5e667ae8b5c2cec44dccd0
homepage   : https://github.com/vinceliuice/vimix-gtk-themes
license    : GPL-3.0-only
component  : desktop.theme
summary    : Vimix is a flat Material Design theme for GTK 2, GTK 3, GTK 4 and Gnome-Shell
description: |
    Vimix is a flat Material Design theme for GTK 2, GTK 3, GTK 4 and Gnome-Shell.
builddeps  :
    - gnome-shell
    - sassc
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
install    : |
    install -dm00644 $installdir/usr/share/themes
    ./install.sh -d $installdir/usr/share/themes -n Vimix -t all -s all
    rm -rf $installdir/usr/share/themes/Vimix*/{cinnamon,unity,xfwm4}
    rm -f $installdir/usr/share/themes/*/{AUTHORS,LICENSE}
